/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "eu-west-1",
  aws_cognito_identity_pool_id:
    "eu-west-1:036b2f8a-485b-41c7-8641-d7fe7e3c8555",
  aws_cognito_region: "eu-west-1",
  aws_user_pools_id: "eu-west-1_anNiAroWc",
  aws_user_pools_web_client_id: "3qgu64ssjurtl6qf1834u88fp0",
  oauth: {},
  aws_cognito_username_attributes: ["EMAIL"],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ["EMAIL"],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ["EMAIL"],
  geo: {
    amazon_location_service: {
      region: "eu-west-1",
      search_indices: {
        items: ["placeindex2bb0e76a-dev"],
        default: "placeindex2bb0e76a-dev",
      },
      maps: {
        items: {
          "map561290f1-dev": {
            style: "VectorEsriStreets",
          },
        },
        default: "map561290f1-dev",
      },
    },
  },
};

export default awsmobile;
